# Generated by Django 3.2.7 on 2021-11-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melodic', '0002_auto_20211115_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='author',
        ),
    ]
