# Generated by Django 3.2.7 on 2021-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodic', '0005_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='body',
            field=models.CharField(default='No body', max_length=9999),
        ),
    ]
