# Generated by Django 3.2.7 on 2021-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodic', '0004_auto_20211115_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
